## Using NumPy

In [2]:
import numpy as np

## Creating NumPy Arrays

### From a Python List

In [4]:
my_list = [1,2,3]

In [5]:
my_list

[1, 2, 3]

In [6]:
arr = np.array(my_list) #Converting list to a numpy array(1D vector)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]] #list of list

In [9]:
np.array(my_mat) #Converting the list of list to a 2D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [10]:
'''
Creating arrays using numpy libraries itself. 
#arange() works similarly as python range() function
'''
np.arange(0,11) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
#Giving a step size to the numpy array. Here step = 2. So we get only the even numbers
np.arange(0,11,2) 

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [14]:
np.zeros(3) #Creating special numpy arrays(vectors/matrices)

array([0., 0., 0.])

In [19]:
'''
To create a 2D array of zeros we pass a tuple such as here (5,3).
First number in the tuple is the number of rows and second number will be the number of columns
'''
np.zeros((5,3)) 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

###### Below, np.linspace returns 10 evenly spaced numbers betn 0 to 5
###### Notice the difference betn arange and linspace
###### In arange, the third argument defines step size

In [23]:
np.linspace(0,5,10)#linspace returns evenly spaced numbers over a specified interval

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

## eye

Creates an identity matrix

In [14]:
np.eye(4) #creating a identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [25]:
np.random.rand(5) #one dimensional array of random numbers from a uniform distribution.(betn 0 to 1)

array([0.65093707, 0.25438994, 0.30809547, 0.06769627, 0.39233755])

In [27]:
'''
two dimensional matrix of random numbers from a uniform distribution (betn 0 and 1). 
We don't pass tuple here. Here dimension is 5x5
'''
np.random.rand(5,5) 

array([[0.06375563, 0.95397474, 0.81625961, 0.29528102, 0.53408714],
       [0.39300359, 0.45154659, 0.99103262, 0.11859278, 0.43591214],
       [0.20925546, 0.88868702, 0.2617684 , 0.81050171, 0.5009476 ],
       [0.92278429, 0.90958357, 0.94901789, 0.76107872, 0.82960676],
       [0.78404414, 0.36424113, 0.6965863 , 0.90404072, 0.85346932]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [30]:
np.random.randn(2) #Two random samples from Gaussian Distribution

array([-0.69425259,  0.47589272])

In [15]:
np.random.randn(4,4)

array([[-0.02968752, -0.91138209, -1.25233249, -0.04095573],
       [ 0.88000023,  1.17373864,  1.09122781, -1.53730692],
       [-0.26967251,  0.79258116,  0.50803253, -0.14263325],
       [-1.59332482, -0.70858953, -0.36398661, -1.14431   ]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [32]:
'''
#getting a random integers from a low to high number. 
Low is exclusive and high is inclusive. 
Means (0,100) will pick a rand int betn 0 and 99
'''
np.random.randint(1,100) 

21

In [16]:
np.random.randint(1,100,10) #To get 10 random integers betn 1 to 99

array([38, 35, 98, 70, 66, 82, 84, 46, 21, 37])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [22]:
arr = np.arange(25)

In [21]:
arr

array([1, 2, 3])

In [19]:
ranrr = np.random.randint(0,50,10)

## Reshape
Returns an array containing the same data with a new shape.

In [26]:
arr.reshape(5,5) #Reshaping an array. Very Important

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [27]:
ranrr.max() #getting max value of an array

43

In [28]:
ranrr.min() #getting min value of an array

19

In [29]:
ranrr.argmax() #gets index location of max value of an array

8

In [30]:
ranrr.argmin()

2

## Shape

Shape is an attribute that arrays have (not a method):

In [31]:
arr.shape #returns shape of a matrix/vector. Here (25,) means it's a vector with 25 rows

(25,)

In [32]:
arr = arr.reshape(5,5)

In [33]:
arr.shape

(5, 5)

### dtype

You can also grab the data type of the object in the array:

In [52]:
arr.dtype #returns data type in your array

dtype('int32')

#### To avoid typing np.random.randint, you can do it like below

In [53]:
from numpy.random import randint
randint(2,10)

6