# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
arr[8] #Accessing a value at a particular index

8

In [5]:
arr[1:5] #Works similary as Python List

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [18]:
arr[0:5] = 100 #Broadcasting elements in numpy array. We cannot do this in list

In [19]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [20]:
arr = np.arange(0,11)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
slice_of_arr = arr[0:6] #slicing an array and assigning it to another one

When you slice an array in numpy, data is not copied. Rather it is just another view of the original array. Thus chaning values in the slice of array would also change values in the original array. Numpy does that to avoid memory issues with very large arrays. Example below:

In [23]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [24]:
slice_of_arr[:] = 99

In [25]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [48]:
'''
Pay attention when you broadcast values on slices of arrays,
it also changes the values on original array
'''
arr 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

If you specifically need a copy and not a reference to the original array, you can follow the procedure below:

In [27]:
arr_copy = arr.copy()

In [28]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
arr_copy[:] = 100

In [30]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [32]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [34]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [35]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
arr_2d[0][0]

5

In [37]:
arr_2d[0] #getting the whole 0th row

array([ 5, 10, 15])

In [38]:
arr_2d[2][1]

40

In [39]:
'''
You can can access elements in this way also(using comma). 
Element in the 2nd row and 1st column
'''
arr_2d[2,1] 

40

In [40]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [41]:
#Suppose you want to grab 10,15 and 25,30

In [42]:
#To do so grab only the first two row and for column grab columns from 1 to last
arr_2d[:2,1:] 

array([[10, 15],
       [25, 30]])

In [43]:
#Some more examples of 2D array slicing

In [44]:
arr_2d = np.array([[5,10,15,50,60],[20,25,30,21,22],[35,40,45,99,200]])

In [45]:
arr_2d

array([[  5,  10,  15,  50,  60],
       [ 20,  25,  30,  21,  22],
       [ 35,  40,  45,  99, 200]])

In [46]:
#Grab only 30,21,22 and 45,99,200

In [47]:
arr_2d[1:,2:]

array([[ 30,  21,  22],
       [ 45,  99, 200]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [47]:
#We'll see conditional selection which we will be using much more often

In [48]:
arr = np.arange(1,11)

In [49]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
bool_arr = arr > 5 #We'll get boolean values if we compare an array like this

In [52]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [54]:
arr[bool_arr] #returning the elements of array where the boolean conditions hold true

array([ 6,  7,  8,  9, 10])

In [57]:
arr[arr>5] #Doing conditional selection in one step

array([ 6,  7,  8,  9, 10])

In [58]:
arr[arr<3]

array([1, 2])

In [64]:
arr_2d = np.arange(50).reshape(5,10)

In [65]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [62]:
arr_2d[1:3,3:5] #another example of 2D slicing

array([[13, 14],
       [23, 24]])